version: '3.7'
services:
    serverless-lambda-redis:
      container_name: serverless-lambda-redis
      image: redis:latest
      ports:
        - 6379:6379
      restart: always
      #hostname: redis-study
      command: redis-server /usr/local/conf/redis.conf
      volumes:
        - ./data/:/data
        - ./conf/redis.conf:/usr/local/conf/redis.conf