service: sls-lambda-url-test
plugins:
  - serverless-dotenv-plugin
  - serverless-offline

frameworkVersion: "3"

custom:
  service: user

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  vpc:
    securityGroupIds:
      - sg-0727ed749d8e56097
    subnetIds:
      - subnet-04858fbf41c73fffc

package:
  exclude:
    - node_modules/**

functions:
  hello:
    handler: index.handler
    url:
      cors: true
    layers:
      - { Ref: NodeModulesLambdaLayer }

layers:
  nodeModules:
    path: layer
    name: ${self:provider.stage}-${self:custom.service}-nodeModules
    compatibleRuntimes:
      - nodejs14.x
