on:
  push:
    branches:
      - main

name: Deploy to serverless service

jobs:
  server:
    name: Deploy Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name : Node Setting
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Set an Environment Variable # add an environment variable step
        id: get-environment
        run: |
          IFS='/' read -ra vBranch <<< "$GITHUB_REF" # 현재 workflow를 실행한 refs/heads/branch를 '/'를 기준으로 array형태로 vBranch에 저장
          stage=${vBranch[2]}                       # vBranch array중에 2번째(branch)를 stage에 저장
          if [[ $stage == "main" ]]
          then
            stage="prod"
          fi
          echo ::set-output name=stage::$stage        # set-stage-env
          echo ::set-output name=region::"ap-northeast-2"        # set=region-env

      - name: npm install
        run: |
          npm i --production

      - name: npm run layer
        run: |
          npm run layer

      - name: serverless deploy
        uses: serverless/github-action@v3
        with:
          args: deploy --stage=${{ steps.get-environment.outputs.stage }} --region=${{ steps.get-environment.outputs.region }}
        env:
          # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # or if using AWS credentials directly
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
